### ISSUE TITLE
[META] 🏢 Typologie des organisations

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1277]
Objectif : catégoriser les organisation selon leur SIRET en s'inspirant des catégories utilisées sur l'Annuaire :
- Service Public
- Collectivité territoriale
- Entreprise
- Association
- Autre

- [x] Valider la faisabilité technique
Interroger l’Annuaire plutôt que faire notre propre qualification. Tout ce qu’on trouve dans l’annuaire qui n’est pas Service Public, Collectivité territoriale ou association est considéré comme entreprise. 

- [x] Valider le design
![Image](https://github.com/etalab/data.gouv.fr/assets/60264344/f3c7f8df-d7be-44be-8f1e-d2fec9ef8849)
![Image](https://github.com/etalab/data.gouv.fr/assets/60264344/92179cdc-4945-492d-84b7-e8121c7c9111)

- [x] Finir la Siretisation manuel (1493 restant) 

- [ ] https://github.com/datagouv/data.gouv.fr/issues/1352

### Plus tard 

D’autre catégories potentiellement pertinente pourraient être ajoutés par la suite : 
- Enseignement ? (**Établissement public national à caractère scientifique culturel et professionnel)**
- Culture ? : (**Établissement public local culturel**)
- Ministère ?

Dans un second temps il est possible d’envisager d’ouvrir la certification à l’ensemble des organisations en s’appuyant sur les métadonnées déjà existantes.

**Comment by nicolaskempf57** [comment]
Est-ce qu'on veut créer ici un sous-ticket pour les organisations en production qui sont à la fois service public et collectivité territoriale ?

**Comment by maudetes** [comment]
> Est-ce qu'on veut créer ici un sous-ticket pour les organisations en production qui sont à la fois service public et collectivité territoriale ?

Yes :+1:, ticket créé : https://github.com/datagouv/data.gouv.fr/issues/1433
