### ISSUE TITLE
[META] Migration d'api.gouv.fr sur data.gouv.fr

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1372]
Ce ticket résume les actions principales à réaliser pour assurer la migration des API de api.gouv.fr sur data.gouv.fr 

# Produit et déploiement
- [ ] Créer un chan mattermost dédié
- [ ] Migrer les guides
- [ ] Sortir les contacts pour les organisations concernées 
- [ ] Définir le matching des organisations
- [ ] Trancher sur les API serviciels
- [ ] Décider de ce qu'il sera fait du nom de domaine api.gouv.fr
- [ ] Caler stratégie et planning com
- [ ] Décider du futurs des canaux de communication d'api.gouv.fr
- [ ] Définir V1 de l'affichage des dataservices
- [ ] Partager les éléments sur la modération à l'équipe api.gouv.fr
- [ ] Revoir l'arbre de décision de support.data.gouv.fr pour rediriger vers équipe circulation

# Front
- [ ] Front des dataservices ([voir le design de la V0](https://www.figma.com/design/9Ai2c1JrRyFNKDSJOXN9wM/%F0%9F%92%BB-Api-et-donn%C3%A9es-restreintes?node-id=598-18342&t=R3N4UXnsMVFk16mz-4)) @nicolaskempf57 
#1369 

# Back
- [ ] Récupérer les API depuis api.gouv.fr
- [ ] Developper un espace swagger pour remplacer https://api.gouv.fr/documentation
#1353 

Ressource : 
Voir notamment [la presentation](https://docs.google.com/presentation/d/1kUf6FO6wFAw0l99ywGLnnifDZIxCvVgW/edit?usp=sharing&ouid=112089326442780050470&rtpof=true&sd=true)

**Comment by ThibaudDauce** [comment]
@agarrone est-ce qu'on peut fermer ce ticket et peut-être rouvrir d'autres pour les derniers points manquants ?
