### ISSUE TITLE
[meta] POC d'évolution d'hydra pour parsing des données geo

### ISSUE THREAD

**Issue by maudetes** [datagouv/data.gouv.fr#1489]
Voir [les notes sur le parsing des données géo](https://www.notion.so/apigouv/Evolution-de-hydra-pour-parsing-de-donn-es-geo-41209dfa2b9f4c46bb1d8de3d24abd3e).

- [x] https://github.com/datagouv/data.gouv.fr/issues/1486
- [x] https://github.com/datagouv/data.gouv.fr/issues/1487
- [x] https://github.com/datagouv/data.gouv.fr/issues/1488
- [x] https://github.com/datagouv/hydra/pull/260
- [x] https://github.com/datagouv/hydra/pull/278
