### ISSUE TITLE
Nouveau frontend Nuxt

### ISSUE THREAD

**Issue by ThibaudDauce** [datagouv/data.gouv.fr#1537]
**Objectif : https://dev.data.gouv.fr/newadmin qui affiche des pages Nuxt en démo mercredi 23 aprem.**

### Acté

- Priorité au déploiement d'une page minimal vs migration de toutes les pages sans déploiement
- Utilisation de https://www.npmjs.com/package/@datagouv/components/v/1.4.0 dans Nuxt (plutôt que link la version latest que l'on a pas forcément besoin)
- Utilisation du login Jinja pour le moment (sauf en local)

### TODO

- [x] Création d'une page Hello World pour les tests de déploiement "/newadmin/index.vue"
- [x]  Migration des pages de la nouvelle admin dans Nuxt
- [x] Écriture de la nouvelle page user dans Nuxt
- [x] Ajouter https://www.npmjs.com/package/@datagouv/components/v/1.4.0 dans Nuxt
- [x] Voir avec @jordanguedj pour déployer Nuxt en version static sur dev
- [x] Voir avec @jordanguedj pour configurer le reverse proxy dev pour rediriger tous les appels `/newadmin` vers Nuxt à la place de Jinja
- [x] Voir plus de TODO : https://github.com/datagouv/front-end/issues/38

**Comment by nicolaskempf57** [comment]
Nothing left here
