### ISSUE TITLE
[META] Amélioration de l'intégration des dataservices 

### ISSUE THREAD

**Issue by agarrone** [datagouv/data.gouv.fr#1601]
🧘 Stay calm

- [ ] **Fiches API**: API2-291 - Résoudre l'erreur CORS de l'édition du swagger dans la fiche API
- [ ] **Fiches API**: API2-292 - Corriger le label : 'Limite' en 'Limite d'appels' sur la fiche
- [ ] **Fiches API**: API2-300 - Modifier l'intitulé de l'API sirene publique
- [ ] **Admin API**: API2-290 - Résoudre le bug sur la modification des liens depuis un champ description
- [ ] **Admin API**: API2-285 - Corriger les descriptions des fiches qui s'affichent mal
- [ ] **Admin API**: API2-293 - Ne pas mettre de cache lors de la modification d'une fiche API
- [ ] **Admin API**: API2-295 - Corriger l'intitulé de l'aide dans l'interface d'admin : 'Ajouter un lien vers la documentation technique' au lieu de documentation métier
- [ ] **Admin API**: API2-310 - Insérer des sauts de ligne lorsqu'il y a un H(1 2 3) dans le texte de la présentation
- [ ] **Moteur de recherche**: API2-315 - Améliorer la recherche avec filtre sur organisation avec un ' dans l'intitulé (ex : hub'eau)
- [ ] **Moteur de recherche**: API2-314 - Dans le filtre 'organisation', ne pas afficher par défaut les organisations qui n'ont pas d'API
- [ ] **Moteur de recherche**: API2-301 - Corriger le moteur de recherche (sensible à la casse)
- [ ] **Moteur de recherche**: API2-325 - Pas de reconnaissance des synonymes

Règles de gestion à approfondir : 
- [ ] **Règles de gestion**: API2-294 - Comprendre la notion de token et les RG associées
- [ ] **Règles de gestion**: API2-296 - Définir comment est exploitée l'information de la fiche : Lien racine de l'API
- [ ] **Règles de gestion**: API2-298 - Préciser le mode opératoire pour pouvoir modifier une organisation liée à une API
- [ ] **Règles de gestion**: API2-304 - Préciser comment s'affiche le sigle ou acronyme de l'API sur la fiche
- [ ] **Règles de gestion**: API2-309 - Préciser si alerte/notification du FD lorsqu'une nouvelle discussion arrive
- [ ] **Règles de gestion**: API2-320 - Définir dans quel canal mattermost sera notifiée la création de nouvelles API
- [ ] **Règles de gestion**: API2-321 - Préciser quels événements CRUD les notifications mattermost seront déclenchées

Evolutions
- [ ] **Évolutions**: API2-297 - Modifier le titre de l'aide pour le champ Lien racine de l'API
- [ ] **Évolutions**: API2-322 - Adapter le texte de l'aide pour le champ Lien racine de l'API (inclure les précisions sur format non IP, etc)
- [ ] **Évolutions**: API2-299 - Ouvrir la page publique de l'API dans une nouvelle fenêtre depuis l'admin
- [ ] **Évolutions**: API2-311 - Donner la possibilité aux FD de saisir des tags et les utiliser dans le moteur de recherche
- [ ] **Évolutions**: API2-303 - Prendre en compte les URL de monitoring dans le champ disponibilité
- [ ] **Évolutions**: API2-305 - Modifier le nom de la rubrique d'aide 'Ajouter un token'
- [ ] **Évolutions**: API2-317 - Pouvoir ajouter un tag HVD
- [ ] **Évolutions**: API2-324 - Intégrer les arbres de décision sur les fiches API
- [ ] **Évolutions**: API2-319 - Modifier les URL à saisir pour décrire le contrat d'interface (url swagger + doc technique)
- [ ] **Évolutions**: API2-302 - Élargir la notion d'accès restreint
- [ ] **Évolutions**: API2-307 - Modifier le label 'Dernière mise à jour' en 'Dernière mise à jour de la fiche'
- [ ] **Évolutions**: API2-308 - Expliciter le label 'Disponibilité' de la fiche API
- [ ] **Évolutions**: API2-316 - Lorsque le contact de la fiche API est un mail, possibilité d'avoir l'objet du mail pré-rempli lorsque l'on clique dessus

[Voir le Linear](https://linear.app/pole-api/issue/API2-289/remonter-et-suivre-les-anomalies-et-demandes-devolutions-dapigouv-a)
